# Generated by Django 2.0.1 on 2018-06-24 20:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default=None, max_length=200)),
                ('price', models.CharField(default=None, max_length=8)),
                ('size_no', models.CharField(default=None, max_length=10)),
                ('net_amount', models.CharField(default=None, max_length=8)),
                ('time_of_reg', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Quants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_val', models.CharField(default=None, max_length=10)),
                ('quantity', models.CharField(default=None, max_length=5)),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.Product')),
            ],
        ),
        migrations.DeleteModel(
            name='Mussa',
        ),
    ]
