# Generated by Django 2.0.1 on 2018-06-25 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20180625_0145'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100)),
                ('add', models.CharField(default=None, max_length=500)),
                ('email', models.EmailField(max_length=30)),
                ('mode_of_pay', models.CharField(default=None, max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_code', models.CharField(default=None, max_length=10)),
                ('discount_amt', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Quant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_val', models.CharField(default=None, max_length=10)),
                ('quantity', models.CharField(default=None, max_length=5)),
            ],
        ),
        migrations.RemoveField(
            model_name='quants',
            name='size',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size_no',
        ),
        migrations.DeleteModel(
            name='Quants',
        ),
        migrations.AddField(
            model_name='quant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.Product'),
        ),
        migrations.AddField(
            model_name='discount',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.Product'),
        ),
        migrations.AddField(
            model_name='details',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.Product'),
        ),
    ]
