# Generated by Django 2.0.1 on 2018-06-25 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20180625_1759'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_1', models.FileField(upload_to='report/')),
                ('image_2', models.FileField(upload_to='report/')),
                ('image_3', models.FileField(upload_to='report/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.Product')),
            ],
        ),
        migrations.AlterField(
            model_name='detail',
            name='add',
            field=models.TextField(default=None, max_length=500),
        ),
    ]
