# Generated by Django 2.0.1 on 2018-06-27 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_auto_20180626_2000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(default=None, max_length=100)),
                ('size', models.CharField(default=None, max_length=100)),
                ('quantity', models.CharField(default=None, max_length=100)),
                ('disc', models.CharField(default=None, max_length=100)),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.Product')),
            ],
        ),
    ]
