# Generated by Django 2.0.1 on 2018-06-28 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_order_discount_offered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='net_amount',
        ),
        migrations.AddField(
            model_name='order',
            name='net_amount',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='detail',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.Order'),
        ),
    ]
