# Generated by Django 2.0.1 on 2018-06-28 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_auto_20180628_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='email',
            field=models.CharField(max_length=30),
        ),
    ]
