# Generated by Django 2.0.1 on 2018-06-28 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_auto_20180628_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='email',
            field=models.EmailField(default=None, max_length=30),
        ),
    ]
