# Generated by Django 2.0.1 on 2018-06-28 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0012_auto_20180628_2041'),
    ]

    operations = [
        migrations.CreateModel(
            name='Det',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100)),
                ('add', models.TextField(default=None, max_length=500)),
                ('contact', models.CharField(default=None, max_length=10)),
                ('email', models.EmailField(default=None, max_length=30)),
                ('mode_of_pay', models.CharField(default=None, max_length=40)),
                ('deliver', models.CharField(default=None, max_length=40)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.Order')),
            ],
        ),
        migrations.AddField(
            model_name='detail',
            name='contact',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='detail',
            name='deliver',
            field=models.CharField(default=None, max_length=40),
        ),
    ]
