# Generated by Django 2.0.1 on 2018-06-28 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0013_auto_20180629_0223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='item',
        ),
        migrations.DeleteModel(
            name='Detail',
        ),
    ]
