# Generated by Django 2.0.1 on 2018-06-28 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0014_auto_20180629_0241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='det',
            name='mode_of_pay',
        ),
        migrations.AddField(
            model_name='det',
            name='mode',
            field=models.TextField(default=None, max_length=40),
        ),
    ]
