# Generated by Django 2.0.1 on 2018-06-29 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0016_auto_20180629_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='det',
            name='email',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
