# Generated by Django 2.0.1 on 2018-06-29 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0019_auto_20180629_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='det',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cart.Order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='prod',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cart.Product'),
        ),
    ]
