# Generated by Django 2.0.1 on 2018-06-29 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0020_auto_20180629_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='prod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.Product'),
        ),
    ]
